### ISSUE TITLE
Relative link saved for File Reference

### ISSUE THREAD

**Issue by willphdavies** [Solid-Interactive/grasshopper-admin#39]
Since in pretty much all projects we are referencing an S3 bucket, it would be nice to have this done automatically.  In every project I've seen there is some middleware that adds the S3 bucket reference to the file refs.  Automatic would save a lot of dev time

**Comment by travism** [comment]
Hmm, I've seen issues with this when it comes to migrating environments (staging / live). 

I'm not sure we should make this absolute. Wordpress has had an issue with this for a long time. 

I vote that we do not make this change (it's also not an admin issue but a core issue).

**Comment by pajtai** [comment]
I agree with Travis. Storing the fill url would require more migration scripts.
Instead we should make use of / expose the built in core functionality to build the full url from the file reference link:

https://github.com/Solid-Interactive/grasshopper-core-nodejs/blob/master/lib/assets/aws/index.js#L430

Will, can you look into whether this is already possible, and if not, come up with a core ticket to express this?

Closing this ticket.
